-- Seed 2-in-1 gift set catalog SKUs
insert into public.products (
  id,
  name,
  price,
  description,
  category,
  images,
  variants,
  currency,
  available_colors,
  product_code,
  material,
  packing_type,
  master_carton,
  customized,
  min_order_qty
) values
  ('h901','2 in 1 Gift Set',0,'Catalog entry','Diary Gift Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H901',null,null,null,null,1),
  ('h902','2 in 1 Gift Set',0,'Catalog entry','Diary Gift Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H902',null,null,null,null,1),
  ('h903','2 in 1 Gift Set',0,'Catalog entry','Diary Gift Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H903',null,null,null,null,1),
  ('h904','2 in 1 Gift Set',0,'Catalog entry','Diary Gift Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H904',null,null,null,null,1),
  ('h905','2 in 1 Gift Set',0,'Catalog entry','Diary Gift Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H905',null,null,null,null,1),
  ('h906','2 in 1 Gift Set',0,'Catalog entry','Diary Gift Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H906',null,null,null,null,1),
  ('h907','2 in 1 Gift Set',0,'Catalog entry','Diary Gift Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H907',null,null,null,null,1),
  ('h908','2 in 1 Gift Set',0,'Catalog entry','Diary Gift Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H908',null,null,null,null,1),
  ('h909','2 in 1 Gift Set',0,'Catalog entry','Diary & Pen Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H909',null,null,null,null,1),
  ('h910','2 in 1 Gift Set',0,'Catalog entry','Diary & Pen Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H910',null,null,null,null,1),
  ('h911','2 in 1 Gift Set',0,'Catalog entry','Diary & Pen Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H911',null,null,null,null,1),
  ('h912','2 in 1 Gift Set',0,'Catalog entry','Diary & Pen Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H912',null,null,null,null,1),
  ('h913','2 in 1 Gift Set',0,'Catalog entry','Diary & Pen Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H913',null,null,null,null,1),
  ('h914','2 in 1 Gift Set',0,'Catalog entry','Diary & Pen Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H914',null,null,null,null,1),
  ('h915','2 in 1 Gift Set',0,'Catalog entry','Diary & Pen Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H915',null,null,null,null,1),
  ('h916','2 in 1 Gift Set',0,'Catalog entry','Pen & Keychain Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H916',null,null,null,null,1),
  ('h917','2 in 1 Gift Set',0,'Catalog entry','Pen & Keychain Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H917',null,null,null,null,1),
  ('h918','2 in 1 Gift Set',0,'Catalog entry','Pen & Keychain Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H918',null,null,null,null,1),
  ('h919','2 in 1 Gift Set',0,'Catalog entry','Pen & Keychain Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H919',null,null,null,null,1),
  ('h920','2 in 1 Gift Set',0,'Catalog entry','Pen & Keychain Set','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H920',null,null,null,null,1),
  ('h921','2 in 1 Combo Gift Set',0,'Catalog entry','Notebook & Pen','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H921',null,null,null,null,1),
  ('h922','2 in 1 Combo Gift Set',0,'Catalog entry','Notebook & Pen','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H922',null,null,null,null,1),
  ('h923','2 in 1 Combo Gift Set',0,'Catalog entry','Notebook & Pen','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H923',null,null,null,null,1),
  ('h924','2 in 1 Combo Gift Set',0,'Catalog entry','Notebook & Pen','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H924',null,null,null,null,1),
  ('h925','2 in 1 Combo Gift Set',0,'Catalog entry','Notebook & Pen','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H925',null,null,null,null,1),
  ('h926','2 in 1 Combo Gift Set',0,'Catalog entry','Notebook & Pen','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H926',null,null,null,null,1),
  ('h927','2 in 1 Combo Gift Set',0,'Catalog entry','Notebook & Pen','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H927',null,null,null,null,1),
  ('h928','2 in 1 Combo Gift Set',0,'Catalog entry','Notebook & Pen','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H928',null,null,null,null,1),
  ('h929','2 in 1 Combo Gift Set',0,'Catalog entry','Notebook & Pen','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H929',null,null,null,null,1),
  ('h930','2 in 1 Combo Gift Set',0,'Catalog entry','Notebook & Pen','[]'::jsonb,'[]'::jsonb,'INR','[]'::jsonb,'H930',null,null,null,null,1)

on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  price = excluded.price,
  description = excluded.description,
  images = excluded.images,
  variants = excluded.variants,
  currency = excluded.currency,
  available_colors = excluded.available_colors,
  product_code = excluded.product_code,
  min_order_qty = excluded.min_order_qty;
